/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package works.hop.model.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class APhone extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"APhone\",\"namespace\":\"works.hop.model.avro\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"number\",\"type\":\"string\"}]}");
    private static final long serialVersionUID = 6609964213900882173L;
    private static SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<APhone> ENCODER =
            new BinaryMessageEncoder<APhone>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<APhone> DECODER =
            new BinaryMessageDecoder<APhone>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<APhone>
            WRITER$ = (org.apache.avro.io.DatumWriter<APhone>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<APhone>
            READER$ = (org.apache.avro.io.DatumReader<APhone>) MODEL$.createDatumReader(SCHEMA$);
    @Deprecated
    public java.lang.CharSequence type;
    @Deprecated
    public java.lang.CharSequence number;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public APhone() {
    }

    /**
     * All-args constructor.
     *
     * @param type   The new value for type
     * @param number The new value for number
     */
    public APhone(java.lang.CharSequence type, java.lang.CharSequence number) {
        this.type = type;
        this.number = number;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<APhone> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<APhone> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<APhone> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<APhone>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Deserializes a APhone from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a APhone instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static APhone fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new APhone RecordBuilder.
     *
     * @return A new APhone RecordBuilder
     */
    public static works.hop.model.avro.APhone.Builder newBuilder() {
        return new works.hop.model.avro.APhone.Builder();
    }

    /**
     * Creates a new APhone RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new APhone RecordBuilder
     */
    public static works.hop.model.avro.APhone.Builder newBuilder(works.hop.model.avro.APhone.Builder other) {
        if (other == null) {
            return new works.hop.model.avro.APhone.Builder();
        } else {
            return new works.hop.model.avro.APhone.Builder(other);
        }
    }

    /**
     * Creates a new APhone RecordBuilder by copying an existing APhone instance.
     *
     * @param other The existing instance to copy.
     * @return A new APhone RecordBuilder
     */
    public static works.hop.model.avro.APhone.Builder newBuilder(works.hop.model.avro.APhone other) {
        if (other == null) {
            return new works.hop.model.avro.APhone.Builder();
        } else {
            return new works.hop.model.avro.APhone.Builder(other);
        }
    }

    /**
     * Serializes this APhone to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return type;
            case 1:
                return number;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                type = (java.lang.CharSequence) value$;
                break;
            case 1:
                number = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'type' field.
     *
     * @return The value of the 'type' field.
     */
    public java.lang.CharSequence getType() {
        return type;
    }

    /**
     * Sets the value of the 'type' field.
     *
     * @param value the value to set.
     */
    public void setType(java.lang.CharSequence value) {
        this.type = value;
    }

    /**
     * Gets the value of the 'number' field.
     *
     * @return The value of the 'number' field.
     */
    public java.lang.CharSequence getNumber() {
        return number;
    }

    /**
     * Sets the value of the 'number' field.
     *
     * @param value the value to set.
     */
    public void setNumber(java.lang.CharSequence value) {
        this.number = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeString(this.type);

        out.writeString(this.number);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.type = in.readString(this.type instanceof Utf8 ? (Utf8) this.type : null);

            this.number = in.readString(this.number instanceof Utf8 ? (Utf8) this.number : null);

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.type = in.readString(this.type instanceof Utf8 ? (Utf8) this.type : null);
                        break;

                    case 1:
                        this.number = in.readString(this.number instanceof Utf8 ? (Utf8) this.number : null);
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }

    /**
     * RecordBuilder for APhone instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<APhone>
            implements org.apache.avro.data.RecordBuilder<APhone> {

        private java.lang.CharSequence type;
        private java.lang.CharSequence number;

        /**
         * Creates a new Builder
         */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(works.hop.model.avro.APhone.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.type)) {
                this.type = data().deepCopy(fields()[0].schema(), other.type);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.number)) {
                this.number = data().deepCopy(fields()[1].schema(), other.number);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing APhone instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(works.hop.model.avro.APhone other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.type)) {
                this.type = data().deepCopy(fields()[0].schema(), other.type);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.number)) {
                this.number = data().deepCopy(fields()[1].schema(), other.number);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'type' field.
         *
         * @return The value.
         */
        public java.lang.CharSequence getType() {
            return type;
        }


        /**
         * Sets the value of the 'type' field.
         *
         * @param value The value of 'type'.
         * @return This builder.
         */
        public works.hop.model.avro.APhone.Builder setType(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.type = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'type' field has been set.
         *
         * @return True if the 'type' field has been set, false otherwise.
         */
        public boolean hasType() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'type' field.
         *
         * @return This builder.
         */
        public works.hop.model.avro.APhone.Builder clearType() {
            type = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'number' field.
         *
         * @return The value.
         */
        public java.lang.CharSequence getNumber() {
            return number;
        }


        /**
         * Sets the value of the 'number' field.
         *
         * @param value The value of 'number'.
         * @return This builder.
         */
        public works.hop.model.avro.APhone.Builder setNumber(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.number = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'number' field has been set.
         *
         * @return True if the 'number' field has been set, false otherwise.
         */
        public boolean hasNumber() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'number' field.
         *
         * @return This builder.
         */
        public works.hop.model.avro.APhone.Builder clearNumber() {
            number = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public APhone build() {
            try {
                APhone record = new APhone();
                record.type = fieldSetFlags()[0] ? this.type : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.number = fieldSetFlags()[1] ? this.number : (java.lang.CharSequence) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }
}










