const FETCH_TODOS = 'FETCH_TODOS';
const CREATE_TODO = 'CREATE_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';

export {FETCH_TODOS, CREATE_TODO, REMOVE_TODO, UPDATE_TODO}